[package]
name = "deep-learning-with-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.9.0", features = ["wgpu", "autodiff", "train"] }
burn-wgpu = "0.9.0"
serde = "1"